# Site
repository: asbelt67/asbelt67.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Austin Belt
title: XXX
email: austinbelt67@gmail.com
website: www.github.com/asbelt67

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: asbelt67
github_username:  asbelt67
# stackoverflow_username: "XXX"
# dribbble_username: XXX
# facebook_username: XXX
# flickr_username: XXX
# instagram_username: XXX
# linkedin_username: XXX
# xing_username: XXX
# pinterest_username: XXX
# youtube_username: XXX
# googleplus_username: XXX
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
- #title: itsgoingto.be
  #icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  XXX
  
  XXX
  
  Email: austinbelt67@gmail.com
  Phone: (765) 491-4060

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: XXX
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          XXX
          
      - layout: top-middle
        title: XXX
        description: |
          XXX
      
      - layout: top-middle
        title: XXX
        description: |
          XXX
          
  - title: Programming History
    layout: list
    content:
      title: XXX
          
  - title: Work History # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: XXX
        link: XXX
        sub_title: XXX
        caption: XXX(date
        description: | # this will include new lines to allow paragraphs
            XXX
            
            
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: North Newton Jr./Sr. High School
        caption: 2013 - 2019
        sub_title: High School Diploma
        description: |
          XXX
        
      - layout: left
        title: Ball State University
        caption: 2019 - present
        sub_title: Bachelor's Degree - Computer Science
        description: | # this will include new lines to allow paragraphs
          XXX
          

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
        XXX

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
